let physicalCurrencies = {
  AED: 'United Arab Emirates Dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Dutch Guilders',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Convertible Mark',
  BBD: 'Barbadian Dollar',
  BDT: 'Bangladeshi Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudian Dollar',
  BND: 'Bruneian Dollar',
  BOB: 'Bolivian Boliviano',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BZD: 'Belizean Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHF: 'Swiss Franc',
  CLF: 'Chilean Unit of Account UF',
  CLP: 'Chilean Peso',
  CNH: 'Chinese Yuan Offshore',
  CNY: 'Chinese Yuan',
  COP: 'Colombian Peso',
  CUP: 'Cuban Peso',
  CVE: 'Cape Verdean Escudo',
  CZK: 'Czech Republic Koruna',
  DJF: 'Djiboutian Franc',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  EUR: 'Euro',
  FJD: 'Fijian Dollar',
  FKP: 'Falkland Islands Pound',
  GBP: 'British Pound Sterling',
  GEL: 'Georgian Lari',
  GHS: 'Ghanaian Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Gambian Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Guatemalan Quetzal',
  GYD: 'Guyanaese Dollar',
  HKD: 'Hong Kong Dollar',
  HNL: 'Honduran Lempira',
  HRK: 'Croatian Kuna',
  HTG: 'Haitian Gourde',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli New Sheqel',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Icelandic Krona',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Japanese Yen',
  KES: 'Kenyan Shilling',
  KGS: 'Kyrgystani Som',
  KHR: 'Cambodian Riel',
  KMF: 'Comorian Franc',
  KPW: 'North Korean Won',
  KRW: 'South Korean Won',
  KWD: 'Kuwaiti Dinar',
  KYD: 'Caymanian Dollar',
  KZT: 'Kazakhstani Tenge',
  LAK: 'Laotian Kip',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lankan Rupee',
  LRD: 'Liberian Dollar',
  LSL: 'Basotho Maloti',
  LYD: 'Libyan Dinar',
  MAD: 'Moroccan Dirham',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Macedonian Denar',
  MMK: 'Myanma Kyat',
  MNT: 'Mongolian Tugrik',
  MOP: 'Macanese Pataca',
  MRU: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MVR: 'Maldivian Rufiyaa',
  MWK: 'Malawian Kwacha',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  MZN: 'Mozambican Metical',
  NAD: 'Namibian Dollar',
  NGN: 'Nigerian Naira',
  NOK: 'Norwegian Krone',
  NPR: 'Nepalese Rupee',
  NZD: 'New Zealand Dollar',
  OMR: 'Omani Rial',
  PAB: 'Panamanian Balboa',
  PEN: 'Peruvian Nuevo Sol',
  PGK: 'Papua New Guinean Kina',
  PHP: 'Philippine Peso',
  PKR: 'Pakistani Rupee',
  PLN: 'Polish Zloty',
  PYG: 'Paraguayan Guarani',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RSD: 'Serbian Dinar',
  RUB: 'Russian Ruble',
  RWF: 'Rwandan Franc',
  SAR: 'Saudi Arabian Riyal',
  SCR: 'Seychellois Rupee',
  SDG: 'Sudanese Pound',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  SHP: 'Saint Helena Pound',
  SLL: 'Sierra Leonean Leone',
  SOS: 'Somali Shilling',
  SRD: 'Surinamese Dollar',
  SYP: 'Syrian Pound',
  SZL: 'Swazi Emalangeni',
  THB: 'Thai Baht',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  TND: 'Tunisian Dinar',
  TOP: "Tongan Pa'anga",
  TRY: 'Turkish Lira',
  TTD: 'Trinidad and Tobago Dollar',
  TWD: 'Taiwan New Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Ukrainian Hryvnia',
  UGX: 'Ugandan Shilling',
  USD: 'United States Dollar',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistan Som',
  VND: 'Vietnamese Dong',
  VUV: 'Ni-Vanuatu Vatu',
  WST: 'Samoan Tala',
  XAF: 'CFA Franc BEAC',
  XCD: 'East Caribbean Dollar',
  XDR: 'Special Drawing Rights',
  XOF: 'CFA Franc BCEAO',
  XPF: 'CFP Franc',
  YER: 'Yemeni Rial',
  ZAR: 'South African Rand',
  ZMW: 'Zambian Kwacha',
};

let cryptoCurrencies = {
  '1INCH': '1inch Network',
  AAVE: 'Aave',
  ACA: 'Acala Token',
  ACH: 'Alchemy Pay',
  ACM: 'AC Milan Fan Token',
  ADA: 'Cardano',
  ADX: 'Ambire AdEx',
  AERGO: 'Aergo',
  AGIX: 'SingularityNET',
  AGLD: 'Adventure Gold',
  AIOZ: 'AIOZ Network',
  AKRO: 'Akropolis',
  ALCX: 'Alchemix',
  ALGO: 'Algorand',
  ALICE: 'MyNeighborAlice',
  ALPHA: 'Alpha Venture DAO',
  ALPINE: 'Alpine F1 Team Fan Token',
  AMB: 'AirDAO',
  AMP: 'Amp',
  ANKR: 'Ankr',
  ANT: 'Aragon',
  APE: 'ApeCoin',
  API3: 'API3',
  APT: 'Aptos',
  AR: 'Arweave',
  ARPA: 'ARPA',
  ASTR: 'Astar',
  ATA: 'Automata Network',
  ATOM: 'Cosmos',
  AUDIO: 'Audius',
  AURORA: 'Aurora',
  AVA: 'Travala.com',
  AVAX: 'Avalanche',
  AXS: 'Axie Infinity',
  BADGER: 'Badger DAO',
  BAL: 'Balancer',
  BAND: 'Band Protocol',
  BAT: 'Basic Attention Token',
  BCH: 'Bitcoin Cash',
  BEL: 'Bella Protocol',
  BICO: 'Biconomy',
  BIFI: 'Beefy Finance',
  BLZ: 'Bluzelle',
  BNB: 'BNB',
  BNT: 'Bancor',
  BOBA: 'Boba Network',
  BOND: 'BarnBridge',
  BOSON: 'Boson Protocol',
  BSW: 'Biswap',
  BTC: 'Bitcoin',
  BTT: 'BitTorrent-New',
  BUSD: 'Binance USD',
  C98: 'Coin98',
  CAKE: 'PancakeSwap',
  CELO: 'Celo',
  CELR: 'Celer Network',
  CFX: 'Conflux',
  CHR: 'Chromia',
  CHZ: 'Chiliz',
  CITY: 'Manchester City Fan Token',
  CKB: 'Nervos Network',
  CLV: 'CLV',
  COMP: 'Compound',
  COTI: 'COTI',
  CQT: 'Covalent',
  CREAM: 'Cream Finance',
  CRO: 'Cronos',
  CRV: 'Curve DAO Token',
  CSPR: 'Casper',
  CTC: 'Creditcoin',
  CTSI: 'Cartesi',
  CUDOS: 'CUDOS',
  CULT: 'Cult DAO',
  CVX: 'Convex Finance',
  DAI: 'Dai',
  DAR: 'Mines of Dalarnia',
  DASH: 'Dash',
  DATA: 'Streamr',
  DCR: 'Decred',
  DEGO: 'Dego Finance',
  DENT: 'Dent',
  DERC: 'DeRace',
  DEXE: 'DeXe',
  DFI: 'DeFiChain',
  DGB: 'DigiByte',
  DIA: 'DIA',
  DODO: 'DODO',
  DOGE: 'Dogecoin',
  DOT: 'Polkadot',
  DUSK: 'Dusk Network',
  DYDX: 'dYdX',
  EGLD: 'Elrond',
  ELF: 'aelf',
  ELON: 'Dogelon Mars',
  ENJ: 'Enjin Coin',
  ENS: 'Ethereum Name Service',
  EOS: 'EOS',
  ETC: 'Ethereum Classic',
  ETH: 'Ethereum',
  ETHW: 'EthereumPoW',
  EVER: 'Everscale',
  FARM: 'Harvest Finance',
  FET: 'Fetch.ai',
  FIDA: 'Bonfida',
  FIL: 'Filecoin',
  FIS: 'StaFi',
  FLOW: 'Flow',
  FLUX: 'Flux',
  FORT: 'Forta',
  FORTH: 'Ampleforth Governance Token',
  FRONT: 'Frontier',
  FTM: 'Fantom',
  FTT: 'FTX Token',
  FXS: 'Frax Share',
  GAL: 'Galatasaray Fan Token',
  GALA: 'Gala',
  GAS: 'Gas',
  GHST: 'Aavegotchi',
  GLM: 'Golem',
  GLMR: 'Moonbeam',
  GMT: 'GMT Token',
  GMX: 'GMX',
  GNO: 'Gnosis',
  GODS: 'Gods Unchained',
  GRT: 'The Graph',
  GST: 'Green Satoshi Token (SOL)',
  GTC: 'Gitcoin',
  HARD: 'Kava Lend',
  HBAR: 'Hedera',
  HERO: 'Metahero',
  HIGH: 'Highstreet',
  HNT: 'Helium',
  HOT: 'Holo',
  ICP: 'Internet Computer',
  ICX: 'ICON',
  ID: 'Everest',
  IDEX: 'IDEX',
  ILV: 'Illuvium',
  IMX: 'Immutable X',
  INJ: 'Injective',
  IOST: 'IOST',
  IOTX: 'IoTeX',
  JASMY: 'JasmyCoin',
  JOE: 'JOE',
  JST: 'JUST',
  JUV: 'Juventus Fan Token',
  KAS: 'Kaspa',
  KAVA: 'Kava',
  KDA: 'Kadena',
  KLAY: 'Klaytn',
  KNC: 'Kyber Network Crystal v2',
  KOK: 'KOK',
  KRL: 'Kryll',
  KSM: 'Kusama',
  LDO: 'Lido DAO',
  LEVER: 'LeverFi',
  LINA: 'Linear Finance',
  LINK: 'Chainlink',
  LIT: 'Litentry',
  LOKA: 'League of Kingdoms Arena',
  LOOKS: 'LooksRare',
  LPT: 'Livepeer',
  LQTY: 'Liquity',
  LRC: 'Loopring',
  LSK: 'Lisk',
  LTC: 'Litecoin',
  LTO: 'LTO Network',
  LUNA: 'Terra',
  LUNC: 'Terra Classic',
  MAGIC: 'MAGIC',
  MANA: 'Decentraland',
  MASK: 'Mask Network',
  MATIC: 'Polygon',
  MBL: 'MovieBloc',
  MDT: 'Measurable Data Token',
  METIS: 'MetisDAO',
  MINA: 'Mina',
  MKR: 'Maker',
  MLN: 'Enzyme',
  MOVR: 'Moonriver',
  MTL: 'Metal DAO',
  MV: 'GensoKishi Metaverse',
  MXC: 'MXC',
  NEAR: 'NEAR Protocol',
  NEO: 'Neo',
  NEXO: 'Nexo',
  NFT: 'APENFT',
  NKN: 'NKN',
  NMR: 'Numeraire',
  OCEAN: 'Ocean Protocol',
  OGN: 'Origin Protocol',
  OM: 'MANTRA',
  OMG: 'OMG Network',
  ONE: 'BigONE Token',
  ONT: 'Ontology',
  OP: 'Optimism',
  ORBS: 'Orbs',
  ORCA: 'Orca',
  ORN: 'Orion Protocol',
  OSMO: 'Osmosis',
  OXT: 'Orchid',
  PAXG: 'PAX Gold',
  PENDLE: 'Pendle',
  PEOPLE: 'ConstitutionDAO',
  PERP: 'Perpetual Protocol',
  PHA: 'Phala Network',
  PLA: 'PlayDapp',
  POLS: 'Polkastarter',
  POND: 'Marlin',
  POWR: 'Powerledger',
  PROM: 'Prom',
  PSG: 'Paris Saint-Germain Fan Token',
  PSTAKE: 'pSTAKE Finance',
  PUNDIX: 'Pundi X (New)',
  PYR: 'Vulcan Forged PYR',
  QI: 'BENQI',
  QKC: 'QuarkChain',
  QNT: 'Quant',
  QTUM: 'Qtum',
  QUICK: 'QuickSwap',
  RACA: 'RadioCaca',
  RAD: 'Radicle',
  RARE: 'SuperRare',
  RARI: 'Rarible',
  REEF: 'Reef',
  REN: 'Ren',
  REQ: 'Request',
  RLC: 'iExec RLC',
  RNDR: 'Render Token',
  ROSE: 'Oasis Network',
  RPL: 'Rocket Pool',
  RSR: 'Reserve Rights',
  RUNE: 'THORChain',
  RVN: 'Ravencoin',
  SAND: 'The Sandbox',
  SC: 'Siacoin',
  SCRT: 'Secret',
  SFP: 'SafePal',
  SFUND: 'Seedify.fund',
  SHIB: 'Shiba Inu',
  SHILL: 'SHILL Token',
  SIDUS: 'SIDUS',
  SKL: 'SKALE Network',
  SLP: 'Smooth Love Potion',
  SNX: 'Synthetix',
  SOL: 'Solana',
  SPELL: 'Spell Token',
  SSV: 'ssv.network',
  STG: 'Stargate Finance',
  STORJ: 'Storj',
  STRAX: 'Stratis',
  STX: 'Stacks',
  SUN: 'Sun (New)',
  SUPER: 'SuperFarm',
  SUSHI: 'SushiSwap',
  SWEAT: 'Sweat Economy',
  SXP: 'SXP',
  SYN: 'Synapse',
  SYS: 'Syscoin',
  T: 'Threshold',
  TFUEL: 'Theta Fuel',
  THETA: 'Theta Network',
  TLM: 'Alien Worlds',
  TON: 'Tokamak Network',
  TRAC: 'OriginTrail',
  TRB: 'Tellor',
  TRU: 'TrueFi',
  TRVL: 'TRVL',
  TRX: 'TRON',
  TUSD: 'TrueUSD',
  TVK: 'Virtua',
  TWT: 'Trust Wallet Token',
  UMA: 'UMA',
  UNFI: 'Unifi Protocol DAO',
  UNI: 'UNICORN Token',
  USDC: 'USD Coin',
  USDD: 'USDD',
  USDP: 'Pax Dollar',
  USDT: 'Tether',
  USTC: 'TerraClassicUSD',
  VEGA: 'Vega Protocol',
  VELO: 'Velo',
  VET: 'VeChain',
  VOXEL: 'Voxies',
  VRA: 'Verasity',
  WAVES: 'Waves',
  WAXP: 'WAX',
  WBTC: 'Wrapped Bitcoin',
  WEMIX: 'WEMIX',
  WIN: 'WINkLink',
  WOO: 'WOO Network',
  WRX: 'WazirX',
  XCAD: 'XCAD Network',
  XDC: 'XDC Network',
  XEC: 'eCash',
  XEM: 'NEM',
  XLM: 'Stellar',
  XMR: 'Monero',
  XNO: 'Xeno Token',
  XRP: 'XRP',
  XTZ: 'Tezos',
  XWG: 'X World Games',
  XYM: 'Symbol',
  XYO: 'XYO',
  YFI: 'yearn.finance',
  YGG: 'Yield Guild Games',
  ZEC: 'Zcash',
  ZEN: 'Horizen',
  ZIL: 'Zilliqa',
  ZRX: '0x',
};

let combinedObj = {...physicalCurrencies, ...cryptoCurrencies};

let allCurrencies = Object.keys(combinedObj)
      .sort()
      .reduce((acc, key) => {
          acc[key] = combinedObj[key];
          return acc;
      }, {});

let physicalCurrenciesKeys = Object.keys(physicalCurrencies);
let cryptoCurrenciesKeys = Object.keys(cryptoCurrencies);
let allCurrenciesKeys = Object.keys(allCurrencies);



module.exports = {
  physicalCurrencies,
  cryptoCurrencies,
  allCurrencies,
  physicalCurrenciesKeys, 
  cryptoCurrenciesKeys,
  allCurrenciesKeys
}