let physicalCurrencies = {
  AED: 'United Arab Emirates Dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Convertible Mark',
  BBD: 'Barbadian Dollar',
  BDT: 'Bangladeshi Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudan Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Bolivian Boliviano',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BYN: 'New Belarusian Ruble',
  BYR: 'Belarusian Ruble',
  BZD: 'Belize Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHF: 'Swiss Franc',
  CLF: 'Chilean Unit of Account (UF)',
  CLP: 'Chilean Peso',
  CNY: 'Chinese Yuan',
  CNH: 'Chinese Yuan Offshore',
  COP: 'Colombian Peso',
  CRC: 'Costa Rican Colón',
  CUC: 'Cuban Convertible Peso',
  CUP: 'Cuban Peso',
  CVE: 'Cape Verdean Escudo',
  CZK: 'Czech Republic Koruna',
  DJF: 'Djiboutian Franc',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  EUR: 'Euro',
  FJD: 'Fijian Dollar',
  FKP: 'Falkland Islands Pound',
  GBP: 'British Pound Sterling',
  GEL: 'Georgian Lari',
  GGP: 'Guernsey Pound',
  GHS: 'Ghanaian Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Gambian Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Guatemalan Quetzal',
  GYD: 'Guyanaese Dollar',
  HKD: 'Hong Kong Dollar',
  HNL: 'Honduran Lempira',
  HRK: 'Croatian Kuna',
  HTG: 'Haitian Gourde',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli New Sheqel',
  IMP: 'Manx pound',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Icelandic Króna',
  JEP: 'Jersey Pound',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Japanese Yen',
  KES: 'Kenyan Shilling',
  KGS: 'Kyrgystani Som',
  KHR: 'Cambodian Riel',
  KMF: 'Comorian Franc',
  KPW: 'North Korean Won',
  KRW: 'South Korean Won',
  KWD: 'Kuwaiti Dinar',
  KYD: 'Cayman Islands Dollar',
  KZT: 'Kazakhstani Tenge',
  LAK: 'Laotian Kip',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lankan Rupee',
  LRD: 'Liberian Dollar',
  LSL: 'Lesotho Loti',
  LTL: 'Lithuanian Litas',
  LVL: 'Latvian Lats',
  LYD: 'Libyan Dinar',
  MAD: 'Moroccan Dirham',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Macedonian Denar',
  MMK: 'Myanma Kyat',
  MNT: 'Mongolian Tugrik',
  MOP: 'Macanese Pataca',
  MRO: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MVR: 'Maldivian Rufiyaa',
  MWK: 'Malawian Kwacha',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  MZN: 'Mozambican Metical',
  NAD: 'Namibian Dollar',
  NGN: 'Nigerian Naira',
  NIO: 'Nicaraguan Córdoba',
  NOK: 'Norwegian Krone',
  NPR: 'Nepalese Rupee',
  NZD: 'New Zealand Dollar',
  OMR: 'Omani Rial',
  PAB: 'Panamanian Balboa',
  PEN: 'Peruvian Nuevo Sol',
  PGK: 'Papua New Guinean Kina',
  PHP: 'Philippine Peso',
  PKR: 'Pakistani Rupee',
  PLN: 'Polish Zloty',
  PYG: 'Paraguayan Guarani',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RSD: 'Serbian Dinar',
  RUB: 'Russian Ruble',
  RWF: 'Rwandan Franc',
  SAR: 'Saudi Riyal',
  SBD: 'Solomon Islands Dollar',
  SCR: 'Seychellois Rupee',
  SDG: 'Sudanese Pound',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  SHP: 'Saint Helena Pound',
  SLL: 'Sierra Leonean Leone',
  SOS: 'Somali Shilling',
  SRD: 'Surinamese Dollar',
  STD: 'São Tomé and Príncipe Dobra',
  SVC: 'Salvadoran Colón',
  SYP: 'Syrian Pound',
  SZL: 'Swazi Lilangeni',
  THB: 'Thai Baht',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  TND: 'Tunisian Dinar',
  TOP: 'Tongan Paʻanga',
  TRY: 'Turkish Lira',
  TTD: 'Trinidad and Tobago Dollar',
  TWD: 'New Taiwan Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Ukrainian Hryvnia',
  UGX: 'Ugandan Shilling',
  USD: 'United States Dollar',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistan Som',
  VEF: 'Venezuelan Bolívar Fuerte',
  VES: 'Sovereign Bolivar',
  VND: 'Vietnamese Dong',
  VUV: 'Vanuatu Vatu',
  WST: 'Samoan Tala',
  XAF: 'CFA Franc BEAC',
  XAG: 'Silver (troy ounce)',
  XAU: 'Gold (troy ounce)',
  XCD: 'East Caribbean Dollar',
  XDR: 'Special Drawing Rights',
  XOF: 'CFA Franc BCEAO',
  XPF: 'CFP Franc',
  YER: 'Yemeni Rial',
  ZAR: 'South African Rand',
  ZMK: 'Zambian Kwacha (pre-2013)',
  ZMW: 'Zambian Kwacha',
  ZWL: 'Zimbabwean Dollar',
};
let cryptoCurrencies = {
    '611': 'SixEleven',
    ABC: 'AB-Chain',
    ACP: 'Anarchists Prime',
    ACT: 'ACT',
    'ACT*': 'Achain',
    ADA: 'Cardano',
    ADCN: 'Asiadigicoin',
    ADL: 'Adelphoi',
    ADX: 'AdEx',
    ADZ: 'Adzcoin',
    AE: 'Aeternity',
    AGI: 'SingularityNET',
    AIB: 'AdvancedInternetBlock',
    AIDOC: 'AI Doctor',
    AION: 'Aion',
    AIR: 'AirToken',
    ALT: 'ALTcoin',
    AMB: 'Ambrosus',
    AMM: 'MicroMoney',
    ANT: 'Aragon',
    APC: 'AlpaCoin',
    APPC: 'AppCoins',
    ARC: 'ArcticCoin',
    ARCT: 'ArbitrageCT',
    ARDR: 'Ardor',
    ARK: 'ARK',
    ARN: 'Aeron',
    ASAFE2: 'Allsafe',
    AST: 'AirSwap',
    ATB: 'ATB coin',
    ATM: 'ATMChain',
    AURS: 'Aureus',
    AVAX: 'Avalanche',
    AVT: 'AventCoin',
    BAR: 'TBIS token',
    BASH: 'LuckChain',
    BAT: 'Basic Attention Token',
    BAY: 'BitBay',
    BBP: 'BiblePay',
    BCD: 'Bitcoin Diamond',
    BCH: 'Bitcoin Cash / BCC',
    BCN: 'ByteCoin',
    BCPT: 'BlockMason Credit Protocol',
    BEE: 'Bee Token',
    BIO: 'Biocoin',
    BLC: 'BlakeCoin',
    BLOCK: 'BlockNet',
    BLU: 'BlueCoin',
    BLZ: 'Bluzelle',
    BMC: 'Blackmoon Crypto',
    BNB: 'Binance Coin',
    BNT: 'Bancor Network Token',
    BOST: 'BoostCoin',
    BQ: 'Bitqy',
    BQX: 'Ethos',
    BRD: 'Bread token',
    BRIT: 'BritCoin',
    BT1: 'Bitfinex Bitcoin Future',
    BT2: 'Bitcoin SegWit2X',
    BTC: 'Bitcoin',
    BTCA: 'Bitair',
    BTCS: 'Bitcoin Scrypt',
    BTCZ: 'BitcoinZ',
    BTG: 'Bitcoin Gold',
    BTLC: 'BitLuckCoin',
    BTM: 'BitMark',
    'BTM*': 'Bytom',
    BTQ: 'BitQuark',
    BTS: 'Bitshares',
    BTX: 'Bitcore',
    BURST: 'BurstCoin',
    CALC: 'CaliphCoin',
    CAS: 'Cashaa',
    CAT: 'BlockCAT',
    CCRB: 'CryptoCarbon',
    CDT: 'CoinDash',
    CESC: 'Crypto Escudo',
    CHAT: 'ChatCoin',
    CJ: 'CryptoJacks',
    CL: 'CoinLancer',
    CLD: 'Cloud',
    CLOAK: 'CloakCoin',
    'CMT*': 'CyberMiles',
    CND: 'Cindicator',
    CNX: 'Cryptonex',
    CPC: 'CapriCoin',
    CRAVE: 'CraveCoin',
    CRC: 'CrowdCoin',
    CRE: 'Credits',
    CRW: 'Crown Coin',
    CTO: 'Crypto',
    CTR: 'Centra',
    CVC: 'Civic',
    DAS: 'DAS',
    DASH: 'DigitalCash',
    DAT: 'Datum',
    DATA: 'Streamr DATAcoin',
    DBC: 'DeepBrain Chain',
    DBET: 'Decent.bet',
    DCN: 'Dentacoin',
    DCR: 'Decred',
    DCT: 'Decent',
    DEEP: 'Deep Gold',
    DENT: 'Dent',
    DGB: 'DigiByte',
    DGD: 'Digix DAO',
    DIM: 'DIMCOIN',
    DIME: 'DimeCoin',
    DMD: 'Diamond',
    DNT: 'district0x',
    DOGE: 'Dogecoin',
    DRGN: 'Dragonchain',
    DRZ: 'Droidz',
    DSH: 'Dashcoin',
    DTA: 'Data',
    EC: 'Eclipse',
    EDG: 'Edgeless',
    EDO: 'Eidoo',
    EDR: 'E-Dinar Coin',
    EKO: 'EchoLink',
    ELA: 'Elastos',
    ELF: 'aelf',
    EMC: 'Emercoin',
    EMGO: 'MobileGo',
    ENG: 'Enigma',
    ENJ: 'Enjin Coin',
    EOS: 'EOS',
    ERT: 'Esports.com',
    ETC: 'Ethereum Classic',
    ETH: 'Ethereum',
    ETN: 'Electroneum',
    ETP: 'Metaverse',
    ETT: 'EncryptoTel',
    EVR: 'Everus',
    EVX: 'Everex',
    FCT: 'Factoids',
    FLP: 'Gameflip',
    FOTA: 'Fortuna',
    FRST: 'FirstCoin',
    FUEL: 'Etherparty',
    FUN: 'FunFair',
    FUNC: 'FunCoin',
    FUTC: 'FutCoin',
    GAME: 'Gamecredits',
    GAS: 'Gas',
    GBYTE: 'Byteball',
    GMX: 'Goldmaxcoin',
    GNO: 'Gnosis',
    GNT: 'Golem Network Token',
    GNX: 'Genaro Network',
    GRC: 'GridCoin',
    GRS: 'Groestlcoin ',
    GRWI: 'Growers International',
    GTC: 'Game',
    GTO: 'GIFTO',
    GUP: 'Guppy',
    GVT: 'Genesis Vision',
    GXS: 'GXShares',
    HAC: 'Hackspace Capital',
    HNC: 'Hellenic Coin',
    HSR: 'Hshare',
    HST: 'Decision Token',
    HVN: 'Hive Project',
    ICN: 'Iconomi',
    ICOS: 'ICOBox',
    ICX: 'ICON Project',
    IGNIS: 'Ignis',
    ILC: 'ILCoin',
    INK: 'Ink',
    INS: 'INS Ecosystem',
    INSN: 'Insane Coin',
    INT: 'Internet Node Token',
    IOP: 'Internet of People',
    IOST: 'IOS token',
    ITC: 'IoT Chain',
    KCS: 'Kucoin',
    KICK: 'KickCoin',
    KIN: 'Kin',
    KLC: 'KiloCoin',
    KMD: 'Komodo',
    KNC: 'Kyber Network',
    KRB: 'Karbo',
    LA: 'LATOKEN',
    LEND: 'EthLend',
    LEO: 'LEOcoin',
    LINDA: 'Linda',
    LINK: 'ChainLink',
    LOC: 'Loco',
    LOG: 'Wood Coin',
    LRC: 'Loopring',
    LSK: 'Lisk',
    LTC: 'Litecoin',
    LUN: 'Lunyr',
    LUX: 'LUXCoin',
    MAID: 'MaidSafe Coin',
    MANA: 'Decentraland',
    MCAP: 'MCAP',
    MCO: 'Monaco',
    MDA: 'Moeda',
    MDS: 'MediShares',
    MIOTA: 'IOTA',
    MKR: 'Maker',
    MLN: 'Melon',
    MNX: 'MinexCoin',
    MOD: 'Modum',
    MOIN: 'MoinCoin',
    MONA: 'MonaCoin',
    MTL: 'Metal',
    'MTN*': 'Medicalchain',
    MTX: 'Matryx',
    NAS: 'Nebulas',
    NAV: 'NavCoin',
    NBT: 'NuBits',
    NDC: 'NeverDie',
    NEBL: 'Neblio',
    NEO: 'NEO',
    NEU: 'Neumark',
    NEWB: 'Newbium',
    NGC: 'NagaCoin',
    NKC: 'Nukecoinz',
    NLC2: 'NoLimitCoin',
    NMC: 'NameCoin',
    NMR: 'Numerai',
    NULS: 'Nuls',
    NVC: 'NovaCoin',
    NXT: 'Nxt',
    OAX: 'OpenANX',
    OBITS: 'Obits Coin',
    OC: 'OrangeCoin',
    OCN: 'Odyssey',
    ODN: 'Obsidian',
    OK: 'OKCash',
    OMG: 'OmiseGo',
    OMNI: 'Omni',
    ORE: 'Galactrum',
    ORME: 'Ormeus Coin',
    OST: 'Simple Token',
    OTN: 'Open Trading Network',
    OTX: 'Octanox',
    OXY: 'Oxycoin',
    PART: 'Particl',
    PAY: 'TenX',
    PBT: 'Primalbase',
    PCS: 'Pabyosi Coin',
    PIVX: 'Private Instant Verified Transaction',
    PIZZA: 'PizzaCoin',
    PLBT: 'Polybius',
    PLR: 'Pillar',
    POE: 'Po.et',
    POLY: 'PolyBit',
    POSW: 'PoSWallet',
    POWR: 'Power Ledger',
    PPC: 'PeerCoin',
    PPT: 'Populous',
    PPY: 'Peerplays',
    PRC: 'ProsperCoin',
    PRES: 'President Trump',
    PRG: 'Paragon',
    PRL: 'Oyster Pearl',
    PRO: 'Propy',
    PURA: 'Pura',
    PUT: 'PutinCoin',
    QASH: 'Quoine Liquid',
    QAU: 'Quantum',
    QSP: 'Quantstamp',
    QTUM: 'QTUM',
    QUN: 'QunQun',
    R: 'Revain',
    RBIES: 'Rubies',
    RCN: 'Ripio',
    RDD: 'ReddCoin',
    RDN: 'RadonPay',
    'RDN*': 'Raiden Network',
    REBL: 'Rebellious',
    REE: 'ReeCoin',
    REP: 'Augur',
    REQ: 'Request Network',
    REV: 'Revenu',
    RGC: 'RG Coin',
    RHOC: 'RChain',
    RIYA: 'Etheriya',
    RKC: 'Royal Kingdom Coin',
    RLC: 'iEx.ec',
    RPX: 'Red Pulse',
    RUFF: 'Ruff',
    SALT: 'Salt Lending',
    SAN: 'Santiment',
    SBC: 'StableCoin',
    SC: 'Siacoin',
    SENT: 'Sentinel',
    SHIFT: 'Shift',
    SIB: 'SibCoin',
    SMART: 'SmartCash',
    SMLY: 'SmileyCoin',
    'SMT*': 'SmartMesh',
    SNC: 'SunContract',
    SNGLS: 'SingularDTV',
    SNM: 'SONM',
    SNT: 'Status Network Token',
    SOL: 'Solana',
    SPK: 'Sparks',
    SRN: 'SirinLabs',
    STEEM: 'Steem',
    STK: 'STK Token',
    STORJ: 'Storj',
    STRAT: 'Stratis',
    STU: 'BitJob',
    STX: 'Stox',
    SUB: 'Substratum Network',
    SUR: 'Suretly',
    SWFTC: 'SwftCoin',
    SYS: 'SysCoin',
    TAAS: 'Token as a Service',
    TESLA: 'TeslaCoilCoin',
    THC: 'The Hempcoin',
    THETA: 'Theta',
    THS: 'TechShares',
    TIO: 'Trade.io',
    TKN: 'TokenCard  ',
    TKY: 'THEKEY Token',
    TNB: 'Time New Bank',
    TNT: 'Tierion',
    TOA: 'TOA Coin',
    TRC: 'TerraCoin',
    TRIG: 'Trigger',
    TRST: 'TrustCoin',
    TRUMP: 'TrumpCoin',
    TRX: 'Tronix',
    UBQ: 'Ubiq',
    UNO: 'Unobtanium',
    UNRC: 'UniversalRoyalCoin',
    UQC: 'Uquid Coin',
    USDT: 'Tether',
    UTK: 'Utrust',
    UTT: 'United Traders Token',
    VEE: 'BLOCKv',
    VEN: 'Vechain',
    VERI: 'Veritaseum',
    VIA: 'ViaCoin',
    VIB: 'Viberate',
    VIBE: 'VIBEHub',
    VOISE: 'Voise',
    VOX: 'Voxels',
    VRS: 'Veros',
    VTC: 'VertCoin',
    VUC: 'Virta Unique Coin',
    WABI: 'WaBi',
    WAVES: 'Waves',
    WAX: 'Worldwide Asset eXchange',
    WC: 'WhiteCoin',
    WGR: 'Wagerr',
    WINGS: 'Wings DAO',
    WLK: 'Wolk',
    WOP: 'WorldPay',
    WPR: 'WePower',
    WRC: 'Worldcore',
    WTC: 'Waltonchain',
    XAUR: 'Xaurum',
    XBP: 'Black Pearl Coin',
    XBY: 'XtraBYtes',
    XCP: 'CounterParty',
    XCXT: 'CoinonatX',
    XDN: 'DigitalNote ',
    XEM: 'NEM',
    XGB: 'GoldenBird',
    XHI: 'HiCoin',
    XID: 'Sphre AIR',
    XLM: 'Stellar',
    XMR: 'Monero',
    XNC: 'XenCoin',
    XRB: 'Nano',
    XRP: 'Ripple',
    XTO: 'Tao',
    XTZ: 'Tezos',
    XUC: 'Exchange Union',
    XVG: 'Verge',
    XZC: 'ZCoin',
    YEE: 'Yee',
    YOC: 'YoCoin',
    YOYOW: 'Yoyow',
    ZBC: 'Zilbercoin',
    ZCL: 'ZClassic',
    ZEC: 'ZCash',
    ZEN: 'ZenCash',
    ZIL: 'Zilliqa',
    ZNY: 'BitZeny',
    ZRX: '0x',
    ZSC: 'Zeusshield'
  };

let combinedObj = {...physicalCurrencies, ...cryptoCurrencies};

let allCurrencies = Object.keys(combinedObj)
      .sort()
      .reduce((acc, key) => {
          acc[key] = combinedObj[key];
          return acc;
      }, {});

let physicalCurrenciesKeys = Object.keys(physicalCurrencies);
let cryptoCurrenciesKeys = Object.keys(cryptoCurrencies);
let allCurrenciesKeys = Object.keys(allCurrencies);

module.exports = {
    allCurrencies,
    allCurrenciesKeys
}